WebShop/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShop.DAL;
using WebShop.CustomObjects;
using WebShop.Models;
using WebShop.BusinessLayer;

namespace WebShop.Controllers
{
    public class ArticlesController : Controller
    {
        private WebShopEntities db = new WebShopEntities();

        [HttpGet]
        public ActionResult Index()
        {
            var categorie = BLCategories.GetAllData();
            SelectList list = new SelectList(categorie,"CAT_ID","CAT_Libelle");
            ViewBag.Categorie = list;
            var souscategorie = BLSousCategories.GetAllData();
            SelectList liste = new SelectList(souscategorie, "SCAT_CAT_Id", "SCAT_Libelle");
            ViewBag.SousCategorie = liste;
            List<ArticlesModel> lstArticle =BLArticles.GetAllData();

            var panier = new Panier();
            var art = new Article();

            if (panier.ArticleId > 0)
            {
                int resultat;
                resultat = art.ART_Stock - panier.ArticleId;
            }
            return View(lstArticle);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Article.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ART_SCAT_Id = new SelectList(db.SousCategorie, "SCAT_Id", "SCAT_Libelle");
            //return View();
            return PartialView("_Create");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(ArticlesModel Article)
        {
            if (ModelState.IsValid)
            {
                BLArticles.AjouterArticle(Article);
                //db.SaveChanges();
                //return RedirectToAction("Index");
                return Json(new { result = "ok" });
            }

            ViewBag.ART_SCAT_Id = new SelectList(db.SousCategorie, "SCAT_Id", "SCAT_Libelle", Article.ART_SCAT_Id);
            return View(Article);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var article = BLArticles.FindArticleById(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.ART_SCAT_Id = new SelectList(db.SousCategorie, "SCAT_Id", "SCAT_Libelle", article.ART_SCAT_Id);
            return View(article);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticlesModel Article)
        {
            if (ModelState.IsValid)
            {
                var article = BLArticles.Edit(Article);
                return RedirectToAction("Index");
            }
            ViewBag.ART_SCAT_Id = new SelectList(db.SousCategorie, "SCAT_Id", "SCAT_Libelle", Article.ART_SCAT_Id);
            return View(Article);

        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var article = BLArticles.FindArticleById(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BLArticles.DeleteById(id);

            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [HttpGet]
        public JsonResult GetCategorie(int catid)
        {
            var art = BLArticles.GetAllData().ToList();
            var sousCat = BLSousCategories.GetAllData().FindAll(x => x.SCAT_CAT_Id == catid).ToList();
            var articles = new List<ArticlesModel>();

            foreach (var sc in sousCat)
            {
                foreach (var a in art)
                {
                    if (a.SousCategorie.SCAT_Id == sc.SCAT_Id)
                    {
                        articles.Add(a);
                    }
                }
            }

            return Json(new { souscat = sousCat, articles = articles }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebShop/Controllers/PanierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.DAL;
using WebShop.BusinessLayer;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class PanierController : Controller
    {
        private WebShopEntities dbContext = new WebShopEntities();

            [HttpGet]
        public ActionResult Index()
        {
            var lst = (List<Article>)Session["Articles"];

            if (lst != null)
            {
                var article = lst.GroupBy(x => x.ART_Libelle).ToList()
                    .Select(x => new WebShop.DAL.Panier()
                    {
                        Article = new Article { ART_Libelle = x.Key, ART_Prix = BLArticles.GetByName(x.Key).ART_Prix, ART_Id = BLArticles.GetByName(x.Key).ART_Id },
                        Count = x.Count(),
                    }).ToList();

                var viewModel = new PanierModel
                {
                    CartItems = article,
                    CartTotal = ToAdd(article)
                };

            return View(viewModel);
            }
            return RedirectToAction("Index", "Articles");
        }
        private decimal ToAdd(List<DAL.Panier> lst)
        {
            decimal total = 0;

            foreach (var item in lst)
            {
                total += item.Article.ART_Prix * item.Count;
            }
            return total;
        }

        [HttpGet]
        public ActionResult AddToCart(int id)
        {
            var addedAlbum = dbContext.Article
                .Single(art => art.ART_Id == id);

            var lst = (List<Article>)Session["Articles"];
            if(lst!=null)
                lst.Add(addedAlbum);
            BLArticles.AddToCartDecreaseDB(id);
                Session["Articles"] = lst;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {

            var article = dbContext.Article
                .Single(art => art.ART_Id == id);

            var lst = (List<Article>)Session["Articles"];
            if (lst.Count >= 1)
            {
            int index = lst.FindIndex(art => art.ART_Id == id);
                lst.RemoveAt(index);
            }
            BLArticles.RemoveToCartUpdateDB(id);
            Session["Articles"] = lst;


            var results = new ViderPanierModel
            {
                Message = Server.HtmlEncode(article.ART_Libelle) + " has been removed from your shopping cart.",
                
            };



            return Json(results);
        }
        }
    }

WebShop/Views/Articles/Create.cshtml
@model WebShop.Models.ArticlesModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ART_SCAT_Id, "Sous-catégorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ART_SCAT_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ART_SCAT_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebShop/Views/Articles/Delete.cshtml
@model WebShop.Models.ArticlesModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Voulez-vous supprimer cette article ?</h3>
<div>
    <h4>Article</h4>
    <hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ART_Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ART_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ART_Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ART_Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SousCategorie.SCAT_Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SousCategorie.SCAT_Libelle)
        </dd>

    </dl>

   

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour aux articles", "Index")
        </div>
    }
</div>

WebShop/Views/Articles/Details.cshtml
@model DAL.Article

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ART_Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ART_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ART_Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ART_Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ART_Stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SousCategorie.SCAT_Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SousCategorie.SCAT_Libelle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ART_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebShop/Views/Articles/Edit.cshtml
@model WebShop.Models.ArticlesModel

@{
    ViewBag.Title = "Edit";
}

<h2>Modifier</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ART_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ART_SCAT_Id, "Sous-catégorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ART_SCAT_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ART_SCAT_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uploadimage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uploadimage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uploadimage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebShop/Views/Articles/Index.cshtml
@model IEnumerable<WebShop.Models.ArticlesModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (User.IsInRole("Admin"))
{
<p><a href="#" class="btn btn-primary btn-lg" id="btnCreate"> Create</a></p>

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content" id="myModalcontent">
            <div class="modal-header">
                Mon header
            </div>
            <div class="modal-body">
                Ceci est mon body
            </div>
            <div class="modal-footer">
                Mon footer
                <button data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
}
    <div class="form-group">
        @Html.Label("Categorie", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Categorie", ViewBag.Categorie as SelectList, null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("SousCategorie", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SousCategorie", ViewBag.SousCategorie as SelectList, null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>


    <br />
    <br />
    <table id="dt" class="table table-striped table-hover">
        <thead>
            <tr cl="trHeader">
                <th>
                    @Html.DisplayNameFor(model => model.ART_Libelle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ART_Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ART_Prix)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ART_Stock)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ART_Libelle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ART_Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ART_Prix)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ART_Stock)
                    </td>@if (User.IsInRole("Admin"))
                    {
                    <td> 

                            @Html.ActionLink("Edit", "Edit", new { id = item.ART_Id }, new { @class = "btn btn-primary" })
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = item.ART_Id }, new { @class = "btn btn-primary" })

                        
                    </td>
                       }
                      
                    <td>
                        @if ((item.ART_Stock >= 0)&& User.IsInRole("User")) // dans le cas ou il n'y a plus d'article(s)
                        {
                        @Html.ActionLink("Ajouter", "AddToCart", "Panier", new { id = item.ART_Id }, new { @class = "btn btn-primary",  }) <text></text>

                        }
                        else
                        {
                            @*@Html.ActionLink("Ajouter", "AddToCart", "Panier", new { id = item.ART_Id }, new { @class = "btn btn-primary",  }) <text></text>*@

                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

@section Scripts {
    @Scripts.Render("~/bundles/DataTables")
    <script>
    $(document).ready(function () {
        $('#dt').dataTable()
    });
    $(document).ready(function () {
        $("#btnCreate").click(function () {
            //console.log("bouton create click");
            $.ajax({
                type: "GET",
                url: '@Url.Action("Create","Articles")',
                success:
                    function (data) {
                        $("#myModalcontent").html(data);
                        $("#myModal").modal("show");
                    }
            })
        });
        $(".myclassEdit").click(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("Edit","Articles")',
                data: { id: this.id },
                success:
                    function (data) {
                        $("#myModalcontent").html(data);
                        $("#myModal").modal("show");
                    }
            })
        });
        $(document).on('click', "#btnModalEdit", function () {
            //console.log("bouton create modal click");
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit","Articles")',
                data: $("#frmEdit").serialize(),
                success:
                    function (data) {
                        if (data.result == "ok") {
                            $("#myModal").modal("hide");
                            location.reload();
                        }
                        else {
                            $("#myModalcontent").html(data);
                            $("#myModal").modal("show");
                        }
                    }
            })
        });



        $(".myclassDelete").click(function () {
            console.log("delete Articles : " + this.id);
        });
        $(document).on('click', "#btnCreateModal", function () {
            //console.log("bouton create modal click");
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create","Articles")',
                    data: $("#frmCreate").serialize(),
                    success:
                        function (data) {
                            if (data.result == "ok") {
                                $("#myModal").modal("hide");
                                location.reload();
                            }
                            else {
                                $("#myModalcontent").html(data);
                                $("#myModal").modal("show");
                            }
                        }
                })
            });
        });
       
        //Met a jour la liste des sous categories en fonction de la categorie selectionnee
        $().ready(function () {
            $('#Categorie').change(function () {
                $('#dt tbody tr').html("<img src='' />")
                $('#dt tbody tr:first-child').html("Loader")
                $.ajax({
                    type: 'GET',
                    datatype: 'json',
                    url: '@Url.Action("GetCategorie", "Articles")',
                    data: { catid: $('#Categorie').val() },
                    success: function (res) {
                        var items;
                        $('#SousCategorie').html("");
                        $.each(res.souscat, function (k, v) {
                            items +=
                            "<option value='" + v.SCAT_Id + "'>" + v.SCAT_Libelle + "</option>";
                        }   )
                        $('#SousCategorie').html(items);

                        var html = "";

                        $.each(res.articles, function (k, v) {
                            html += '<tr><td>' + v.ART_Libelle + '</td><td>'
                                + v.ART_Description + '</td><td>'
                                + v.ART_Prix + '</td><td>'
                                + v.ART_Stock + '</td><td>'
                                + v.SousCategorie.SCAT_Libelle + '</td><td>'
                                + '<a class="btn btn-primary" href="/Panier/AddToCart/' + v.ART_Id + '">Ajouter</a> | '
                                + '<a class="btn btn-primary" href="/Articles/Details/' + v.ART_Id + '">Details</a></td></tr>';
                        })

                        $('#dt tbody').html(html);
                    }
                })
            })

            $('#SousCategorie').change(function () {
                $('#dt tbody tr').html("<img src='' />")
                $('#dt tbody tr:first-child').html("Loader")

                $.ajax({
                    type: 'GET',
                    datatype: 'json',
                    url: '@Url.Action("GetCategorie", "Articles")',
                    data: { catid: $('#SousCategorie').val() },
                    success: function (res) {
                        var html = "";

                        $.each(res.articles, function (k, v) {
                            html += '<tr><td>' + v.ART_Libelle + '</td><td>'
                                + v.ART_Description + '</td><td>'
                                + v.ART_Prix + '</td><td>'
                                + v.ART_Stock + '</td><td>'
                                + v.SousCategorie.SCAT_Libelle + '</td><td>'
                                + '<a class="btn btn-primary" href="/Panier/AddToCart/' + v.ART_Id + '">Ajouter</a> | '
                                + '<a class="btn btn-primary" href="/Articles/Details/' + v.ART_Id + '">Details</a></td></tr>';
                        })

                        $('#dt tbody').html(html);
                    }
                })
            })
        })
    </script>
    }

WebShop/Views/Articles/_Create.cshtml
@model WebShop.Models.ArticlesModel

@using (Html.BeginForm("Create", "Articles", FormMethod.Post, new { id = "frmCreate" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ART_SCAT_Id, "Catégorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ART_SCAT_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ART_SCAT_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ART_Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ART_Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ART_Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button data-dismiss="modal" class="btn btn-danger">Fermer</button>
                <input type="button" value="Save" class="btn btn-default" id="btnCreateModal" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}